services:
  # Backend API service
  - type: web
    name: chappy
    runtime: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://chappy-frontend.onrender.com

  # Frontend static site
  - type: static
    name: chappy-frontend
    rootDirectory: frontend
    buildCommand: npm install && VITE_API_URL=https://chappy.onrender.com/api npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://chappy.onrender.com/api